eureka:
  client:
    serviceUrl:
      defaultZone: http://47.101.152.143:8761/eureka/,http://47.101.152.143:8762/eureka/
server:
  port: 8765

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled=true: true