server:
  port: 8761

peer:
  port: 8762


spring:
  application:
    name: EurekaServer

eureka:
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://47.101.152.143:${peer.port}/eureka/


